### ISSUE TITLE
Installation without pytest dependency

### ISSUE THREAD

**Issue by ghislainp** [SatCloP/pyrtlib#21]
I'm trying to integrate PyRTlib in SMRT as suggested in your GMD paper.

May I suggest to remove pytest and pytest-datafiles from requirements.txt and move it to dev-requirements.txt ?

**Comment by slarosa** [comment]
Thank you for your suggestion!

Fixed in 9dcb7cd802b08cba9bfbc5c222e38acb71f9a9c6
